### ISSUE TITLE
Reminder for me :)

### ISSUE THREAD

**Issue by Turtl3God7** [Turtl3God7/Python-Distance-Calculator#11]
Anyone reading this, this issue is a reminder for me to debug the saving of carvalues to a list. This is related to that part of modifying the gas calculations.             

 In the `showOne` function, attempting to append to `currentcar` as if it were a list, but `currentcar` is initialized as an integer. This will raise a TypeError. Consider initializing `currentcar` as a list if you intend to append to it. This issue was flagged previously but seems to persist in the current version of the code.

```diff
- currentcar = 0
+ currentcar = []
```

---

<details>
<summary>Committable suggestion</summary>

> :bangbang: **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation.

```suggestion
                currentcar = []
                currentcar.append([row[0], row[1], row[2], row[3], row[4], leasing])
```

</details>

_Originally posted by @coderabbitai[bot] in https://github.com/Turtl3God7/Python-Distance-Calculator/pull/8#discussion_r1499329005_

**Comment by TurtleGod7** [comment]
This should be done in the upcoming release for v2.1. It should release soon🤞(In the next week or 2)
