### ISSUE TITLE
Fully implement the new SQL databse

### ISSUE THREAD

**Issue by Turtl3God7** [Turtl3God7/Python-Distance-Calculator#7]
The database I have used needs to be implemented into the previous code. Some example changes can be:

- Remove previous data saving
- Change all numerical checkers to use the function 
```python
def get_numeric_input():
``` 
- Modify the new saving system to be similar to the previous code (Check the main branch for old car data saving)

**Comment by TurtleGod7** [comment]
In the latest update to the branch we:
- [X] Implemented the new SQL database(no errors)
- [ ] Change wordings to fit the code
- [ ] Edit the code to fit the rest of the code

**Comment by Turtl3God7** [comment]
Don't do 

>  ```python
> def get_numeric_input():
> ```

because it changes how the code checks if a number is a float and how it works with the SQL database.
